source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftLocation_Example', :exclusive => true do
  pod "SwiftLocation", :path => "../"
end

target 'SwiftLocation_Tests', :exclusive => true do
  pod "SwiftLocation", :path => "../"

  pod 'FBSnapshotTestCase'
end
